### ISSUE TITLE
bypass的v2ray依赖可以改为xray吗？

### ISSUE THREAD

**Issue by tefiszx** [garypang13/luci-app-bypass#13]
我把up的app合并到lean的代码里了。lean在不久前删除了源码包中的v2raycore，改用xray替代，**具体参见**[Remove V2Ray: Xray-core will provide #6327](https://github.com/coolsnowwolf/lede/pull/6327)。请问up打算同步替换还是坚持v2raycore的包独立。

**Comment by garypang13** [comment]
默认就是用的xray, 至于v2ray并不是bypass的必选依赖,去不去掉没啥影响的,

**Comment by tefiszx** [comment]
> 默认就是用的xray, 至于v2ray并不是bypass的必选依赖,去不去掉没啥影响的,

谢谢。有空给up推个pr，修改一下Makefile，合并v2ray和Xray，届时请up审核。
