### ISSUE TITLE
has a dependency on 'smartdns-le', which does not exist

### ISSUE THREAD

**Issue by mkmichael** [garypang13/luci-app-bypass#14]
上午更新bypass源码，feeds update是提示“has a dependency on 'smartdns-le', which does not exist”，编译时出错。

另外，若在feeds.conf.default文件中添加src-git，feeds update无法创建index。

基于lean的源码编译，昨天之前git clone 您的bypass源码，按照说明文件，还可以编程成功的。

求助，谢谢！

**Comment by garypang13** [comment]
@mkmichael 新增了个依赖     https://github.com/garypang13/openwrt-packages/tree/master/smartdns-le

**Comment by mkmichael** [comment]
@garypang13 谢谢！
我把smartdns-le复制到packages目录下后，feeds update通过，但是编译的时候与原有的smartdns冲突了，我是passwall+bypass同时编译的。试着删除了smartdns-le文件夹，然后把bypass make file里的“smartdns-le”改成了smartdns，再次编译ok了。不知道这样操作是否影响bypass，新的固件目前使用暂时没发现异常。
再次感谢！
