### ISSUE TITLE
SmartDNS 未运行

### ISSUE THREAD

**Issue by touchsola** [garypang13/luci-app-bypass#21]
开启软件后，日志里面每分钟报 SmartDNS Error. Restart!
smartdns-le 版本 1.2021.02.06-1
OpenWrt SNAPSHOT r16335-8c8496435a

内外网功能正常✔
未开其他DNS服务或者过滤

还请帮忙查阅

![Screenshot_2021-03-25 OpenWrt - 基本设置 - LuCI](https://user-images.githubusercontent.com/72115940/112423841-595b3280-8d6e-11eb-9fc9-d680fdd2250c.png)

**Comment by y9858** [comment]
我这正常
![$E`H L6@TKOLF@C4UC0($AF](https://user-images.githubusercontent.com/53130835/112428066-8e1eb800-8d75-11eb-8432-ad2c4d1dc3be.png)

**Comment by touchsola** [comment]
重启解决90%的问题，又测了几台，没有复现问题

**Comment by henrykey** [comment]
同样的问题，重启没用

**Comment by henrykey** [comment]
> 我这正常 ![$E`H L6@TKOLF@C4UC0($AF](https://user-images.githubusercontent.com/53130835/112428066-8e1eb800-8d75-11eb-8432-ad2c4d1dc3be.png)

请问这些logs怎么看？谢谢
