### ISSUE TITLE
好像是缺少依赖...

### ISSUE THREAD

**Issue by gcphym** [garypang13/luci-app-bypass#3]
小白一枚 lede/package$下运行 ```git clone https://github.com/garypang13/luci-app-bypass``` 然后 ```./scripts/feeds update -a && 
./scripts/feeds install -a``` 最后 ```make menuconfig``` 出现这个提示 ```WARNING: Makefile 'package/luci-app-bypass/Makefile' has a dependency on 'lua-maxminddb', which does not exist``` 想请教下怎么处理 谢谢

**Comment by garypang13** [comment]
https://github.com/garypang13/openwrt-packages/tree/master/lua-maxminddb

**Comment by gcphym** [comment]
谢谢 问题解决了 想问下安装的时候选了这个是不是就不能再装smartdns那些了 会不会冲突

**Comment by garypang13** [comment]
用这个版本的luci-app-smartdns即可  https://github.com/garypang13/openwrt-packages/tree/master/luci-app-smartdns
