### ISSUE TITLE
前天lean的代码更新后bypass就不能编译了

### ISSUE THREAD

**Issue by mmeiwenlong** [garypang13/luci-app-bypass#31]
![photo_2021-05-13_22-39-05](https://user-images.githubusercontent.com/44661424/118147201-ef900880-b441-11eb-950e-7b8370aa503d.jpg)
有请大佬适配，谢谢

**Comment by garypang13** [comment]
已经不需要readme里的
```
find package/*/ feeds/*/ -maxdepth 2 -path "*luci-app-bypass/Makefile" | xargs -i sed -i 's/shadowsocksr-libev-ssr-redir/shadowsocksr-libev-alt/g' {}
find package/*/ feeds/*/ -maxdepth 2 -path "*luci-app-bypass/Makefile" | xargs -i sed -i 's/shadowsocksr-libev-ssr-server/shadowsocksr-libev-server/g' {}
```
这段代码了,

**Comment by mmeiwenlong** [comment]
> 已经不需要readme里的
> 
> ```
> find package/*/ feeds/*/ -maxdepth 2 -path "*luci-app-bypass/Makefile" | xargs -i sed -i 's/shadowsocksr-libev-ssr-redir/shadowsocksr-libev-alt/g' {}
> find package/*/ feeds/*/ -maxdepth 2 -path "*luci-app-bypass/Makefile" | xargs -i sed -i 's/shadowsocksr-libev-ssr-server/shadowsocksr-libev-server/g' {}
> ```
> 
> 这段代码了，

![QQ截图20210514210048](https://user-images.githubusercontent.com/44661424/118274343-9a163300-b4f7-11eb-83e9-7787cfe80f0b.png)
不加好像也不行

**Comment by garypang13** [comment]
你得重新拉去代码

**Comment by mmeiwenlong** [comment]
> 你得重新拉取代码

谢谢。可以了
