### ISSUE TITLE
请问有没有人遇到过订阅自动更新后没有自动运行的问题

### ISSUE THREAD

**Issue by firkerword** [garypang13/luci-app-bypass#4]
使用环境：目前用的是lean的源码，4.19.138内核，编译了passwall、ssrp、bypass等插件，机器为x86，bypass是截止现在最新版
问题描述：因为订阅是默认选择5点更新，第二天发现外网进不去，检查发现bypass没有运行，检查日志也发现在更新完订阅之后就停止了，且订阅也已经更新成功，也没有其他的报错日志，保存应用之后可以运行，20号前的版本没有遇到这种情况，目前暂时判断不了是哪里的问题！

**Comment by zh15933** [comment]
遇到过 看了日志，也是订阅后就再无气质产生

**Comment by zh15933** [comment]
遇到过 看了日志，也是订阅后就再无日志产生
