### ISSUE TITLE
手机页面下，底部的IP检测条会遮挡住应用/保存键

### ISSUE THREAD

**Issue by stephensund** [garypang13/luci-app-bypass#8]
大佬有空可以修复一下这个，还是有点影响使用的。
![20210204_114050](https://user-images.githubusercontent.com/47056935/106842498-1d491100-66df-11eb-905a-fc2c6e9d1450.jpg)

**Comment by garypang13** [comment]
用的是哪个主题

**Comment by stephensund** [comment]
> 
> 
> 用的是哪个主题

argon主题，18.06

**Comment by garypang13** [comment]
已修复.
